### ISSUE TITLE
Provide sensible default network config

### ISSUE THREAD

**Issue by aspiers** [cseader/suse-cloud-appliances#4]
In most cases people will install with standard network setup, i.e. `192.168.124.10`.  So it makes sense to make that the default, and to skip the requirement to go through the annoying yast process.  But of course there still needs to be an option to change it to non-default.

**Comment by cseader** [comment]
I have tested this and have discovered that by doing this it causes problems where people don't want to use the standard network setup. It actually uses this configuration on the first boot and if your physical network does not accommodate the standard network setup then there is not talking to the internet from the image and it can't get past its own ethernet port. 

In order to make this happen I would need to somehow add in some logic in the first boot section which would allow a selection to add in the standard network or configure your own. This would either require that a YaST module be created for this or some other such way I am not aware of. I will do some research to see how flexible the first boot environment can be. It might be possible to take the first boot script that executes before it hits the firstboot.xml and add the logic there and if you take the option for standard network then modify the firstboot.xml so that it disables the network YaST module. Those are my thoughts right now. more tomorrow.

**Comment by aspiers** [comment]
Can't you just keep it how it is except pre-populate the network config with `192.168.124.10` and a hostname of something like `suse-cloud-admin`?

**Comment by cseader** [comment]
I have tried and tested what you have stated and it causes the image to boot with those settings and therefore causes problems in firstboot where it would fit only one scenario. The Network First Boot options don't reload the network to make the changes and from that point it causes problems with NCC, SMT, NTP etc.. if your physical network is not on that default network setup.

**Comment by cseader** [comment]
Further testing and research shows that for populating the DNS you must set it in /etc/sysconfig/network/config under a few variables NETCONFIG_DNS_STATIC_SEARCHLIST, and NETCONFIG_DNS_STATIC_SERVERS and then netconfig will modify /etc/resolv.conf for you and YaST will pull this information in from this file. Making the modifications now and testing.

**Comment by aspiers** [comment]
Just tried this with 1.1.0 and there are no default settings for the network card on firstboot??  Did you fix this and break it again, or am I missing something?
